apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: only-list-secrets-role
  namespace: sec-ctx
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list