apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: only-list-secrets-default-ns
  namespace: sec-ctx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: only-list-secrets-role
subjects:
  - kind: ServiceAccount
    name: only-list-secrets-sa
    namespace: sec-ctx
