apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: list-secrets
  name: list-secrets
spec:
  selector:
    matchLabels:
      run: list-secrets
  template:
    metadata:
      labels:
        run: list-secrets
    spec:
      serviceAccountName: only-list-secrets-sa
      containers:
      - image: raesene/alpine-containertools
        name: list-secrets
        command:
          - "sh"
          - "-c"
          - "while true; do sleep 300; done"